name: Discord Notifications

on:
  pull_request:
    types: [opened, closed, reopened]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]
  push:
    branches:
      - main

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Extract event data
        id: extract_data
        shell: bash
        run: |
          # 이벤트 타입과 기본 정보 추출
          EVENT_NAME="${{ github.event_name }}"
          echo "event_name=$EVENT_NAME" >> $GITHUB_OUTPUT
          
          # 중복 알림 방지를 위한 이벤트 세부 정보 추출
          if [ "$EVENT_NAME" = "pull_request_review_comment" ]; then
            echo "comment_id=${{ github.event.comment.id }}" >> $GITHUB_OUTPUT
            echo "reply_status=$([ -n "${{ github.event.comment.in_reply_to_id }}" ] && echo "reply" || echo "original")" >> $GITHUB_OUTPUT
          elif [ "$EVENT_NAME" = "pull_request_review" ]; then
            echo "review_id=${{ github.event.review.id }}" >> $GITHUB_OUTPUT
            echo "has_comments=$([ -n "${{ github.event.review.body }}" ] && [ "${{ github.event.review.body }}" != "null" ] && echo "true" || echo "false")" >> $GITHUB_OUTPUT
          fi

      - name: Determine Discord message
        id: set_message
        shell: bash
        env:
          EVENT_NAME: ${{ steps.extract_data.outputs.event_name }}
          REPLY_STATUS: ${{ steps.extract_data.outputs.reply_status }}
          HAS_REVIEW_COMMENTS: ${{ steps.extract_data.outputs.has_comments }}
        run: |
          MESSAGE=""
          
          # PR 리뷰 이벤트 - 코멘트가 없거나 리뷰 상태가 "commented"인 경우 스킵
          # 이는 파일 코드 라인 코멘트가 PR 리뷰로도 등록되는 경우를 방지합니다
          if [ "$EVENT_NAME" = "pull_request_review" ]; then
            REVIEW_STATE="${{ github.event.review.state }}"
            if [ "$HAS_REVIEW_COMMENTS" = "false" ] && [ "$REVIEW_STATE" = "commented" ]; then
              echo "Skipping empty review comment notification"
              exit 0
            fi
          fi

          if [ "$EVENT_NAME" = "pull_request" ]; then
            ACTION="${{ github.event.action }}"
            TITLE=$(echo "${{ github.event.pull_request.title }}" | sed 's/"/\\"/g')
            URL="${{ github.event.pull_request.html_url }}"
            
            if [ "$ACTION" = "opened" ]; then
              MESSAGE=":sparkles: 새로운 Pull Request가 생성되었습니다!\\n제목: **$TITLE**\\nURL: $URL"
            elif [ "$ACTION" = "reopened" ]; then
              MESSAGE=":repeat: Pull Request가 다시 열렸습니다!\\n제목: **$TITLE**\\nURL: $URL"
            elif [ "$ACTION" = "closed" ]; then
              if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
                MESSAGE=":white_check_mark: Pull Request가 머지되었습니다!\\n제목: **$TITLE**\\nURL: $URL"
              else
                MESSAGE=":x: Pull Request가 닫혔습니다.\\n제목: **$TITLE**\\nURL: $URL"
              fi
            fi
          
          elif [ "$EVENT_NAME" = "pull_request_review" ]; then
            REVIEWER="${{ github.event.review.user.login }}"
            REVIEW_STATE="${{ github.event.review.state }}"
            TITLE=$(echo "${{ github.event.pull_request.title }}" | sed 's/"/\\"/g')
            URL="${{ github.event.pull_request.html_url }}"
            COMMENT=$(echo "${{ github.event.review.body }}" | sed 's/"/\\"/g' | tr '\n' ' ' | cut -c 1-200)
            
            if [ "$REVIEW_STATE" = "approved" ]; then
              if [ -n "$COMMENT" ] && [ "$COMMENT" != "null" ]; then
                MESSAGE=":white_check_mark: **$REVIEWER**님이 Pull Request를 승인했습니다!\\n코멘트: $COMMENT\\nPull Request: **$TITLE**\\nURL: $URL"
              else
                MESSAGE=":white_check_mark: **$REVIEWER**님이 Pull Request를 승인했습니다!\\nPull Request: **$TITLE**\\nURL: $URL"
              fi
            elif [ "$REVIEW_STATE" = "changes_requested" ]; then
              if [ -n "$COMMENT" ] && [ "$COMMENT" != "null" ]; then
                MESSAGE=":warning: **$REVIEWER**님이 Pull Request에 변경을 요청했습니다!\\n코멘트: $COMMENT\\nPull Request: **$TITLE**\\nURL: $URL"
              else
                MESSAGE=":warning: **$REVIEWER**님이 Pull Request에 변경을 요청했습니다!\\nPull Request: **$TITLE**\\nURL: $URL"
              fi
            elif [ "$REVIEW_STATE" = "commented" ] && [ -n "$COMMENT" ] && [ "$COMMENT" != "null" ]; then
              # 단일 코드 라인 코멘트 이벤트와 중복되지 않도록 전체 PR 코멘트만 처리
              MESSAGE=":speech_balloon: **$REVIEWER**님이 PR 전체에 리뷰 코멘트를 남겼습니다!\\nPull Request: **$TITLE**\\n코멘트: $COMMENT\\nURL: $URL"
            fi
          
          elif [ "$EVENT_NAME" = "pull_request_review_comment" ]; then
            # 파일의 특정 라인에 대한 단일 코멘트 처리
            AUTHOR="${{ github.event.comment.user.login }}"
            # 봇 댓글 필터링
            if [[ "$AUTHOR" == *[Bb][Oo][Tt]* ]]; then
              echo "Bot comment detected, skipping notification"
              exit 0
            fi
            
            PR_TITLE=$(echo "${{ github.event.pull_request.title }}" | sed 's/"/\\"/g')
            COMMENT_BODY=$(echo "${{ github.event.comment.body }}" | sed 's/"/\\"/g' | tr '\n' ' ' | cut -c 1-200)
            COMMENT_URL="${{ github.event.comment.html_url }}"
            FILE_PATH="${{ github.event.comment.path }}"
            LINE="${{ github.event.comment.line }}"
            
            # 답글인지 확인하고 아이콘과 메시지 포맷 변경
            if [ "$REPLY_STATUS" = "reply" ]; then
              MESSAGE=":twisted_rightwards_arrows: **$AUTHOR**님이 파일 코드 코멘트에 답글을 남겼습니다!\\nPR: **$PR_TITLE**\\n파일: \`$FILE_PATH:$LINE\`\\n답글: $COMMENT_BODY\\nURL: $COMMENT_URL"
            else
              MESSAGE=":mag: **$AUTHOR**님이 파일 코드 라인에 코멘트를 남겼습니다!\\nPR: **$PR_TITLE**\\n파일: \`$FILE_PATH:$LINE\`\\n코멘트: $COMMENT_BODY\\nURL: $COMMENT_URL"
            fi
          
          elif [ "$EVENT_NAME" = "issue_comment" ]; then
            # PR 댓글인지 확인
            if [ -n "${{ github.event.issue.pull_request }}" ]; then
              AUTHOR="${{ github.event.comment.user.login }}"
              # 봇 댓글 필터링
              if [[ "$AUTHOR" == *[Bb][Oo][Tt]* ]]; then
                echo "Bot comment detected, skipping notification"
                exit 0
              fi
              
              COMMENT=$(echo "${{ github.event.comment.body }}" | sed 's/"/\\"/g' | tr '\n' ' ' | cut -c 1-200)
              # 코멘트가 비어있으면 알림 생성하지 않음
              if [ -z "$COMMENT" ] || [ "$COMMENT" = "null" ]; then
                echo "Empty comment detected, skipping notification"
                exit 0
              fi
              
              COMMENT_TRUNCATED=$([ ${#COMMENT} -gt 200 ] && echo "... (더 보려면 링크 클릭)" || echo "")
              CMT_URL="${{ github.event.comment.html_url }}"
              TITLE=$(echo "${{ github.event.issue.title }}" | sed 's/"/\\"/g')
              
              # 답글 여부 확인 개선
              if [ -z "${{ github.event.comment.in_reply_to_id }}" ]; then
                MESSAGE=":speech_balloon: **$AUTHOR**님이 PR에 새 코멘트를 남겼습니다!\\nPR: **$TITLE**\\n코멘트: $COMMENT$COMMENT_TRUNCATED\\nURL: $CMT_URL"
              else
                MESSAGE=":repeat: **$AUTHOR**님이 PR 코멘트에 답글을 남겼습니다!\\nPR: **$TITLE**\\n답글: $COMMENT$COMMENT_TRUNCATED\\nURL: $CMT_URL"
              fi
            fi
          
          elif [ "$EVENT_NAME" = "push" ]; then
            # 봇 커밋 필터링
            AUTHOR="${{ github.event.head_commit.author.name }}"
            if [[ "$AUTHOR" == *[Bb][Oo][Tt]* ]]; then
              echo "Bot push detected, skipping notification"
              exit 0
            fi
            
            COMMIT_MESSAGE=$(echo "${{ github.event.head_commit.message }}" | sed 's/"/\\"/g' | tr '\n' ' ' | cut -c 1-200)
            COMMIT_MESSAGE_TRUNCATED=$([ ${#COMMIT_MESSAGE} -gt 200 ] && echo "... (더 보려면 링크 클릭)" || echo "")
            COMMIT_URL="${{ github.event.head_commit.url }}"
            REPO="${{ github.repository }}"
            
            MESSAGE=":rocket: **$REPO** 저장소의 main 브랜치에 새 커밋!\\n작성자: **$AUTHOR**\\n메시지: $COMMIT_MESSAGE$COMMIT_MESSAGE_TRUNCATED\\nURL: $COMMIT_URL"
          fi

          # 메시지가 비어있지 않은 경우에만 출력
          if [ -n "$MESSAGE" ]; then
            # 2000자 제한 적용
            MESSAGE="${MESSAGE:0:1950}"
            # 환경에 저장
            echo "has_message=true" >> $GITHUB_OUTPUT
            echo "discord_message=$MESSAGE" >> $GITHUB_OUTPUT
          else
            echo "has_message=false" >> $GITHUB_OUTPUT
          fi

      - name: Send notification to Discord
        if: steps.set_message.outputs.has_message == 'true'
        env:
          DISCORD_MESSAGE: ${{ steps.set_message.outputs.discord_message }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # 정확한 JSON 형식으로 페이로드 생성
          payload=$(cat <<EOF
          {
            "content": "$DISCORD_MESSAGE"
          }
          EOF
          )
          
          # curl 명령에 오류 출력 및 재시도 로직 추가
          max_retries=3
          for ((i=1; i<=max_retries; i++)); do
            response=$(curl -s -f -H "Content-Type: application/json" \
              -d "$payload" \
              "$DISCORD_WEBHOOK_URL" 2>&1)
            
            if [ $? -eq 0 ]; then
              echo "Discord notification sent successfully!"
              exit 0
            else
              echo "Attempt $i failed: $response"
              if [ $i -lt $max_retries ]; then
                echo "Retrying in 2 seconds..."
                sleep 2
              else
                echo "All attempts failed"
                exit 1
              fi
            fi
          done
